# Generated by Django 5.2.8 on 2025-12-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
