# Generated by Django 5.2.8 on 2025-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0003_taskmodel_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_comp',
            field=models.BooleanField(default=False),
        ),
    ]
